server:
  port: ${ENV_PORT}

spring:
  flyway:
    out-of-order: true
    baseline-version : 0
    baseline-on-migrate: true
    ignore-migration-patterns:
      - "*:missing"
      - "*:future"

  config:
    import: optional:configtree:/run/secrets/ , optional:file:.env[.properties]
  application:
    name: auth_server
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
logging:
  level:
    org.springframework.security: ${ DEBUG }

jwt:
  key:
    id: 'configured-f57f-46a2-b502-8a24c308be7f'
    public: classpath:app.pub
    private: classpath:app.key


mail:
  username: ${MAIL}


