server:
  port: ${ENV_PORT}

spring:
  flyway:
    baseline-version : 0
    baseline-on-migrate: true

  config:
    import: optional:configtree:/run/secrets/ , optional:file:.env[.properties]
  application:
    name: auth_server
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.security: ${ DEBUG }

jwt:
  key:
    id: 'configured-f57f-46a2-b502-8a24c308be7f'
    public: classpath:app.pub
    private: classpath:app.key


mail:
  username: ${MAIL}


