DROP TYPE IF EXISTS donations_frequency_enum;
CREATE TYPE "donations_frequency_enum" AS ENUM (
    'monthly',
    'quarterly',
    'yearly'
    );

CREATE TABLE "roles"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        VARCHAR(50) UNIQUE NOT NULL,
    "description" TEXT
);

CREATE TABLE "permissions"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        VARCHAR(100) UNIQUE NOT NULL,
    "description" TEXT
);

CREATE TABLE "role_permissions"
(
    "role_id"       INT,
    "permission_id" INT,
    PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "users"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "full_name"  VARCHAR(255)        NOT NULL,
    "email"      VARCHAR(255) UNIQUE NOT NULL,
    "phone"      VARCHAR(50),
    "password"   VARCHAR(255)        NOT NULL,
    "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
    "updated_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
    "role_id"    INT
);

CREATE TABLE "campaigns"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"           VARCHAR(255)   NOT NULL,
    "description"    TEXT           NOT NULL,
    "target_amount"  DECIMAL(10, 2) NOT NULL,
    "current_amount" DECIMAL(10, 2) DEFAULT 0,
    "start_date"     DATE           NOT NULL,
    "end_date"       DATE           NOT NULL,
    "is_approved"    BOOLEAN        DEFAULT false
);

CREATE TABLE "donations"
(
    "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "donor_id"      INT                      NOT NULL,
    "campaign_id"   INT                      NOT NULL,
    "amount_base"   DECIMAL(10, 2)           NOT NULL,
    "amount_total"  DECIMAL(10, 2)           NOT NULL,
    "donation_date" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
    "frequency"     donations_frequency_enum NOT NULL
);

CREATE TABLE "recurring_donations"
(
    "id"                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "donation_id"        INT  NOT NULL,
    "next_donation_date" DATE NOT NULL
);

CREATE TABLE "beneficiaries"
(
    "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"             INT            NOT NULL,
    "campaign_id"         INT            NOT NULL,
    "situation_detail"    TEXT           NOT NULL,
    "support_received"    DECIMAL(10, 2) NOT NULL,
    "verification_status" BOOLEAN DEFAULT false
);

ALTER TABLE "role_permissions"
    ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "role_permissions"
    ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id");

ALTER TABLE "users"
    ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "donations"
    ADD FOREIGN KEY ("donor_id") REFERENCES "users" ("id");

ALTER TABLE "donations"
    ADD FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");

ALTER TABLE "recurring_donations"
    ADD FOREIGN KEY ("donation_id") REFERENCES "donations" ("id");

ALTER TABLE "beneficiaries"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "beneficiaries"
    ADD FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");
