
##---
#spring.profiles: local
#spring.profiles.include: common, queue
#---
#spring.profiles: vps
#spring.profiles.include: common, queue
#---
spring:
  profiles:
    active: common, queue, https, mail
